import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useEffect, ReactElement } from 'react';
import dynamic from 'next/dynamic';

const DynamicMap = dynamic(
  () => {
    return import('../components/Map');
  },
  { ssr: false }
);

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DynamicMap />

      <footer className={styles.footer}>
        <a
          href="https://www.ff-neusiedlamsee.at"
          target="_blank"
          rel="noopener noreferrer"
        >
          Hydranten Karte der Freiwilligen Feuerwehr Neusiedl am See
        </a>
      </footer>
    </div>
  );
};

export default Home;
