/**
 * Default Kostenersatz (Cost Recovery) Rates
 *
 * Based on Burgenland fire brigade cost recovery regulations
 * Landesgesetzblatt Nr. 77/2023
 *
 * These rates are used to seed the Firestore database and can be
 * reset by admins if needed.
 */

import { KostenersatzRate, KostenersatzVersion } from './kostenersatz';

export const DEFAULT_VERSION_ID = 'LGBl_77_2023';

export const DEFAULT_VERSION: KostenersatzVersion = {
  id: DEFAULT_VERSION_ID,
  name: 'LGBl. Nr. 77/2023',
  validFrom: '2023-11-07',
  isActive: true,
  createdAt: new Date().toISOString(),
  createdBy: 'system',
};

/**
 * Default tariff rates based on LGBl. Nr. 77/2023
 *
 * Categories:
 * Tarif A (Categories 1-9):
 *   1 - Mannschaft und Fahrtkostenersatz
 *   2 - Fahrzeuge und Anhänger
 *   3 - Löschgeräte, Schläuche und Zubehör sowie Leitern
 *   4 - Geräte mit motorischem Antrieb
 *   5 - Füllen von Pressluftflaschen
 *   6 - Werkzeuge, Beleuchtungsgeräte und sonstige Einsatzgeräte
 *   7 - Persönliche Ausrüstung - Schutzbekleidung
 *   8 - Wasserdienst
 *   9 - Einsatzgeräte für den Gefährliche-Stoffe-Einsatz
 * Tarif B (Category 10):
 *   10 - Tarif für pauschalierte Beistellungen und Einsatzleistungen
 * Tarif C (Category 11):
 *   11 - Tarif für Brandschutzanlagen
 * Tarif D (Category 12):
 *   12 - Tarif für Verbrauchsmaterialien
 */
export const DEFAULT_RATES: Omit<KostenersatzRate, 'version' | 'validFrom'>[] = [
  // ==========================================================================
  // Category 1: Mannschaft und Fahrtkostenersatz (Personnel & Travel) - Tarif A
  // ==========================================================================
  {
    id: '1.01',
    category: 'A',
    categoryNumber: 1,
    categoryName: 'Mannschaft und Fahrtkostenersatz',
    description: 'Personalaufwand (Einsatz, Bereitschaftsdienste, usw.)',
    unit: 'pro Person & h',
    price: 32.4,
    isExtendable: false,
    sortOrder: 101,
  },
  {
    id: '1.02',
    category: 'A',
    categoryNumber: 1,
    categoryName: 'Mannschaft und Fahrtkostenersatz',
    description: 'Kommissionsdienst durch Feuerwehrorgane',
    unit: 'pro Person & h',
    price: 32.4,
    isExtendable: false,
    sortOrder: 102,
  },
  {
    id: '1.03',
    category: 'A',
    categoryNumber: 1,
    categoryName: 'Mannschaft und Fahrtkostenersatz',
    description:
      'Sachverständigentätigkeit durch Feuerwehrorgane (für Bauverhandlungen, Bauplatzerklärungen und dgl.)',
    unit: 'pro Person & h',
    price: 105.8,
    isExtendable: false,
    sortOrder: 103,
  },
  {
    id: '1.04',
    category: 'A',
    categoryNumber: 1,
    categoryName: 'Mannschaft und Fahrtkostenersatz',
    description: 'Fahrtkostenersatz für Kommissionsdienst',
    unit: 'pro km',
    price: 0.42,
    isExtendable: false,
    sortOrder: 104,
  },

  // ==========================================================================
  // Category 2: Fahrzeuge und Anhänger (Vehicles & Trailers) - Tarif A
  // ==========================================================================
  {
    id: '2.01',
    category: 'A',
    categoryNumber: 2,
    categoryName: 'Fahrzeuge und Anhänger',
    description: 'Fahrzeuge bis 3,5 t Gesamtgewicht',
    unit: 'je Std / 5-12h pauschal',
    price: 63.7,
    pricePauschal: 318.5,
    isExtendable: false,
    sortOrder: 201,
  },
  {
    id: '2.02',
    category: 'A',
    categoryNumber: 2,
    categoryName: 'Fahrzeuge und Anhänger',
    description: 'Fahrzeuge über 3,5 t bis 5,5 t Gesamtgewicht',
    unit: 'je Std / 5-12h pauschal',
    price: 90.7,
    pricePauschal: 453.5,
    isExtendable: false,
    sortOrder: 202,
  },
  {
    id: '2.03',
    category: 'A',
    categoryNumber: 2,
    categoryName: 'Fahrzeuge und Anhänger',
    description: 'Fahrzeuge über 5,5 t bis 7,5 t Gesamtgewicht',
    unit: 'je Std / 5-12h pauschal',
    price: 106.9,
    pricePauschal: 534.5,
    isExtendable: false,
    sortOrder: 203,
  },
  {
    id: '2.04',
    category: 'A',
    categoryNumber: 2,
    categoryName: 'Fahrzeuge und Anhänger',
    description: 'Fahrzeuge über 7,5 t bis 16 t Gesamtgewicht',
    unit: 'je Std / 5-12h pauschal',
    price: 122.0,
    pricePauschal: 610.0,
    isExtendable: false,
    sortOrder: 204,
  },
  {
    id: '2.05',
    category: 'A',
    categoryNumber: 2,
    categoryName: 'Fahrzeuge und Anhänger',
    description: 'Fahrzeuge über 16 t bis 18 t Gesamtgewicht',
    unit: 'je Std / 5-12h pauschal',
    price: 137.1,
    pricePauschal: 685.5,
    isExtendable: false,
    sortOrder: 205,
  },
  {
    id: '2.06',
    category: 'A',
    categoryNumber: 2,
    categoryName: 'Fahrzeuge und Anhänger',
    description: 'Drehleiter, Teleskopmast- bzw. Gelenkbühnen',
    unit: 'je Std / 5-12h pauschal',
    price: 239.7,
    pricePauschal: 1198.5,
    isExtendable: false,
    sortOrder: 206,
  },
  {
    id: '2.07',
    category: 'A',
    categoryNumber: 2,
    categoryName: 'Fahrzeuge und Anhänger',
    description: 'VF mit Gefahrgutausrüstung',
    unit: 'je Std / 5-12h pauschal',
    price: 123.1,
    pricePauschal: 615.5,
    isExtendable: false,
    sortOrder: 207,
  },
  {
    id: '2.08',
    category: 'A',
    categoryNumber: 2,
    categoryName: 'Fahrzeuge und Anhänger',
    description: 'ULF, GTLF',
    unit: 'je Std / 5-12h pauschal',
    price: 197.6,
    pricePauschal: 988.0,
    isExtendable: false,
    sortOrder: 208,
  },
  {
    id: '2.09',
    category: 'A',
    categoryNumber: 2,
    categoryName: 'Fahrzeuge und Anhänger',
    description:
      'Rüstfahrzeug ohne Kran, LKW/WLF mit Kran bis 100 kNm Hubmoment',
    unit: 'je Std / 5-12h pauschal',
    price: 149.0,
    pricePauschal: 745.0,
    isExtendable: false,
    sortOrder: 209,
  },
  {
    id: '2.10',
    category: 'A',
    categoryNumber: 2,
    categoryName: 'Fahrzeuge und Anhänger',
    description:
      'Rüstfahrzeug mit Kran (SRF), LKW/WLF mit Kran über 100 kNm bis 300 kNm Hubmoment',
    unit: 'je Std / 5-12h pauschal',
    price: 181.4,
    pricePauschal: 907.0,
    isExtendable: false,
    sortOrder: 210,
  },
  {
    id: '2.11',
    category: 'A',
    categoryNumber: 2,
    categoryName: 'Fahrzeuge und Anhänger',
    description: 'Kranfahrzeug mit mehr als 300 kN Hubkraft',
    unit: 'je Std / 5-12h pauschal',
    price: 302.4,
    pricePauschal: 1512.0,
    isExtendable: false,
    sortOrder: 211,
  },
  {
    id: '2.12',
    category: 'A',
    categoryNumber: 2,
    categoryName: 'Fahrzeuge und Anhänger',
    description: 'Telelader, Teleskoplader inkl. Anbaugeräte',
    unit: 'je Std / 5-12h pauschal',
    price: 106.9,
    pricePauschal: 534.5,
    isExtendable: false,
    sortOrder: 212,
  },
  {
    id: '2.13',
    category: 'A',
    categoryNumber: 2,
    categoryName: 'Fahrzeuge und Anhänger',
    description: 'Anhänger bis 750 kg Nutzlast',
    unit: 'je Std / 5-12h pauschal',
    price: 17.2,
    pricePauschal: 86.0,
    isExtendable: false,
    sortOrder: 213,
  },
  {
    id: '2.14',
    category: 'A',
    categoryNumber: 2,
    categoryName: 'Fahrzeuge und Anhänger',
    description: 'Anhänger 750 – 3.500 kg Nutzlast',
    unit: 'je Std / 5-12h pauschal',
    price: 51.8,
    pricePauschal: 259.0,
    isExtendable: false,
    sortOrder: 214,
  },
  {
    id: '2.15',
    category: 'A',
    categoryNumber: 2,
    categoryName: 'Fahrzeuge und Anhänger',
    description: 'LKW Anhänger über 3.500 kg Nutzlast',
    unit: 'je Std / 5-12h pauschal',
    price: 75.6,
    pricePauschal: 378.0,
    isExtendable: false,
    sortOrder: 215,
  },
  {
    id: '2.16',
    category: 'A',
    categoryNumber: 2,
    categoryName: 'Fahrzeuge und Anhänger',
    description: 'Wechselladeaufbau Atemluft, GSF, KSF, TDF',
    unit: 'je Std / 5-12h pauschal',
    price: 130.6,
    pricePauschal: 653.0,
    isExtendable: false,
    sortOrder: 216,
  },
  {
    id: '2.17',
    category: 'A',
    categoryNumber: 2,
    categoryName: 'Fahrzeuge und Anhänger',
    description:
      'Wechselladeaufbau Einsatzleitung, Versorgung, Feuerwehrmedizinischer Dienst, Sanitär',
    unit: 'je Std / 5-12h pauschal',
    price: 58.3,
    pricePauschal: 291.5,
    isExtendable: false,
    sortOrder: 217,
  },
  {
    id: '2.18',
    category: 'A',
    categoryNumber: 2,
    categoryName: 'Fahrzeuge und Anhänger',
    description: 'Wechselladeaufbau Schlauch, Tank, Bergung',
    unit: 'je Std / 5-12h pauschal',
    price: 29.1,
    pricePauschal: 145.5,
    isExtendable: false,
    sortOrder: 218,
  },
  {
    id: '2.19',
    category: 'A',
    categoryNumber: 2,
    categoryName: 'Fahrzeuge und Anhänger',
    description: 'Sonstiger Wechselladeaufbau (Pritsche, Mulde)',
    unit: 'je Std / 5-12h pauschal',
    price: 15.1,
    pricePauschal: 75.5,
    isExtendable: false,
    sortOrder: 219,
  },
  {
    id: '2.20',
    category: 'A',
    categoryNumber: 2,
    categoryName: 'Fahrzeuge und Anhänger',
    description: 'Drohne inkl. Führungs- und Transportfahrzeug',
    unit: 'je Std / 5-12h pauschal',
    price: 90.7,
    pricePauschal: 453.5,
    isExtendable: false,
    sortOrder: 220,
  },

  // ==========================================================================
  // Category 3: Löschgeräte, Schläuche und Zubehör sowie Leitern - Tarif A
  // ==========================================================================
  {
    id: '3.01',
    category: 'A',
    categoryNumber: 3,
    categoryName: 'Löschgeräte, Schläuche und Zubehör sowie Leitern',
    description:
      'Trockenlöschgerät P50 (Lösch- und Treibmittel nach Tarif D), Wasserstrahlpumpe',
    unit: 'je Std / 5-12h pauschal',
    price: 16.2,
    pricePauschal: 81.0,
    isExtendable: false,
    sortOrder: 301,
  },
  {
    id: '3.02',
    category: 'A',
    categoryNumber: 3,
    categoryName: 'Löschgeräte, Schläuche und Zubehör sowie Leitern',
    description: 'Trockenlöschgerät TroLA 250 (Lösch- und Treibmittel nach Tarif D)',
    unit: 'je Std / 5-12h pauschal',
    price: 21.6,
    pricePauschal: 108.0,
    isExtendable: false,
    sortOrder: 302,
  },
  {
    id: '3.03',
    category: 'A',
    categoryNumber: 3,
    categoryName: 'Löschgeräte, Schläuche und Zubehör sowie Leitern',
    description: 'Wasserführende Armaturen, Schläuche und Zubehör, je Stk',
    unit: 'je Std / 5-12h pauschal',
    price: 0,
    pricePauschal: 11.8,
    isExtendable: false,
    sortOrder: 303,
  },
  {
    id: '3.04',
    category: 'A',
    categoryNumber: 3,
    categoryName: 'Löschgeräte, Schläuche und Zubehör sowie Leitern',
    description: 'Fahrbare Schiebleiter (nicht hydraulisch)',
    unit: 'je Std / 5-12h pauschal',
    price: 33.4,
    pricePauschal: 167.0,
    isExtendable: false,
    sortOrder: 304,
  },
  {
    id: '3.05',
    category: 'A',
    categoryNumber: 3,
    categoryName: 'Löschgeräte, Schläuche und Zubehör sowie Leitern',
    description: 'Tragbare Leiter, Strickleiter, Rettungsplattform',
    unit: 'je Std / 5-12h pauschal',
    price: 10.8,
    pricePauschal: 54.0,
    isExtendable: false,
    sortOrder: 305,
  },

  // ==========================================================================
  // Category 4: Geräte mit motorischem Antrieb - Tarif A
  // ==========================================================================
  {
    id: '4.01',
    category: 'A',
    categoryNumber: 4,
    categoryName: 'Geräte mit motorischem Antrieb',
    description: 'Handgeführte Elektro- oder Akku-Werkzeuge',
    unit: 'je Std / 5-12h pauschal',
    price: 21.6,
    pricePauschal: 108.0,
    isExtendable: false,
    sortOrder: 401,
  },
  {
    id: '4.02',
    category: 'A',
    categoryNumber: 4,
    categoryName: 'Geräte mit motorischem Antrieb',
    description:
      'Hochleistungslüfter - Turboventilator; Tauchpumpe unter 1.000 l/min, Wassersauger, Motorkettensäge, Ölumfüllpumpe, Benzinmotor-Trennschleifer, Leichtschaumgerät, Hochdruckreiniger',
    unit: 'je Std / 5-12h pauschal',
    price: 29.1,
    pricePauschal: 145.5,
    isExtendable: false,
    sortOrder: 402,
  },
  {
    id: '4.03',
    category: 'A',
    categoryNumber: 4,
    categoryName: 'Geräte mit motorischem Antrieb',
    description:
      'Tauchpumpe von 1.000 l/min bis 2.000 l/min, Auspumpaggregat und Tragkraftspritze bis 1.000 l/min, Stromerzeuger bis 5 kVA',
    unit: 'je Std / 5-12h pauschal',
    price: 38.8,
    pricePauschal: 194.0,
    isExtendable: false,
    sortOrder: 403,
  },
  {
    id: '4.04',
    category: 'A',
    categoryNumber: 4,
    categoryName: 'Geräte mit motorischem Antrieb',
    description:
      'Tauchpumpe über 2.000 l/min, Auspumpaggregat und Tragkraftspritze über 1.000 l/min, Stromerzeuger 5 kVA bis 12 kVA',
    unit: 'je Std / 5-12h pauschal',
    price: 51.8,
    pricePauschal: 259.0,
    isExtendable: false,
    sortOrder: 404,
  },
  {
    id: '4.05',
    category: 'A',
    categoryNumber: 4,
    categoryName: 'Geräte mit motorischem Antrieb',
    description: 'Stromerzeuger von 12 kVA - 20 kVA',
    unit: 'je Std / 5-12h pauschal',
    price: 63.7,
    pricePauschal: 318.5,
    isExtendable: false,
    sortOrder: 405,
  },
  {
    id: '4.06',
    category: 'A',
    categoryNumber: 4,
    categoryName: 'Geräte mit motorischem Antrieb',
    description: 'Stromerzeuger von 21 kVA – 50 kVA',
    unit: 'je Std / 5-12h pauschal',
    price: 75.6,
    pricePauschal: 378.0,
    isExtendable: false,
    sortOrder: 406,
  },
  {
    id: '4.07',
    category: 'A',
    categoryNumber: 4,
    categoryName: 'Geräte mit motorischem Antrieb',
    description: 'Stromerzeuger von 51 kVA – 150 kVA',
    unit: 'je Std / 5-12h pauschal',
    price: 87.4,
    pricePauschal: 437.0,
    isExtendable: false,
    sortOrder: 407,
  },
  {
    id: '4.08',
    category: 'A',
    categoryNumber: 4,
    categoryName: 'Geräte mit motorischem Antrieb',
    description: 'Stromerzeuger über 150 kVA',
    unit: 'je Std / 5-12h pauschal',
    price: 110.1,
    pricePauschal: 550.5,
    isExtendable: false,
    sortOrder: 408,
  },
  {
    id: '4.09',
    category: 'A',
    categoryNumber: 4,
    categoryName: 'Geräte mit motorischem Antrieb',
    description:
      'Akku-/Hydr. Rettungssatz (einschließlich Hydraulikschere und -spreizer) ohne Stromversorgung',
    unit: 'je Std / 5-12h pauschal',
    price: 27.0,
    pricePauschal: 135.0,
    isExtendable: false,
    sortOrder: 409,
  },
  {
    id: '4.10',
    category: 'A',
    categoryNumber: 4,
    categoryName: 'Geräte mit motorischem Antrieb',
    description: 'Auspumpaggregat über 5.000 l/min',
    unit: 'je Std / 5-12h pauschal',
    price: 110.1,
    pricePauschal: 550.5,
    isExtendable: false,
    sortOrder: 410,
  },
  {
    id: '4.11',
    category: 'A',
    categoryNumber: 4,
    categoryName: 'Geräte mit motorischem Antrieb',
    description:
      'Löschunterstützungsfahrzeug (LUF) inkl. Transportanhänger oder Fahrzeug',
    unit: 'je Std / 5-12h pauschal',
    price: 90.7,
    pricePauschal: 453.5,
    isExtendable: false,
    sortOrder: 411,
  },

  // ==========================================================================
  // Category 5: Füllen von Pressluftflaschen - Tarif A
  // ==========================================================================
  {
    id: '5.01',
    category: 'A',
    categoryNumber: 5,
    categoryName: 'Füllen von Pressluftflaschen',
    description: 'Füllen einer Pressluftflasche bis 6 Liter',
    unit: 'je Füllung',
    price: 4.3,
    isExtendable: false,
    sortOrder: 501,
  },
  {
    id: '5.02',
    category: 'A',
    categoryNumber: 5,
    categoryName: 'Füllen von Pressluftflaschen',
    description: 'Füllen einer Pressluftflasche über 6 Liter',
    unit: 'je Füllung',
    price: 6.4,
    isExtendable: false,
    sortOrder: 502,
  },

  // ==========================================================================
  // Category 6: Werkzeuge, Beleuchtungsgeräte und sonstige Einsatzgeräte - Tarif A
  // ==========================================================================
  {
    id: '6.01',
    category: 'A',
    categoryNumber: 6,
    categoryName: 'Werkzeuge, Beleuchtungsgeräte und sonstige Einsatzgeräte',
    description: 'Feldküche',
    unit: 'nach Aufwand',
    price: 0,
    isExtendable: true,
    sortOrder: 601,
  },
  {
    id: '6.02',
    category: 'A',
    categoryNumber: 6,
    categoryName: 'Werkzeuge, Beleuchtungsgeräte und sonstige Einsatzgeräte',
    description:
      'Hebekissen, Hebeballon, Arbeitsdruck über 1 bar (Luft nach Kap. 5)',
    unit: 'je Std / 5-12h pauschal',
    price: 37.8,
    pricePauschal: 189.0,
    isExtendable: false,
    sortOrder: 602,
  },
  {
    id: '6.03',
    category: 'A',
    categoryNumber: 6,
    categoryName: 'Werkzeuge, Beleuchtungsgeräte und sonstige Einsatzgeräte',
    description:
      'Hebekissen, Hebeballon, Arbeitsdruck bis 1 bar (Luft nach Kap. 5)',
    unit: 'je Std / 5-12h pauschal',
    price: 49.6,
    pricePauschal: 248.0,
    isExtendable: false,
    sortOrder: 603,
  },
  {
    id: '6.04',
    category: 'A',
    categoryNumber: 6,
    categoryName: 'Werkzeuge, Beleuchtungsgeräte und sonstige Einsatzgeräte',
    description: 'Zelt, bis 10 Personen',
    unit: 'je Std / 5-12h pauschal',
    price: 0,
    pricePauschal: 47.5,
    isExtendable: false,
    sortOrder: 604,
  },
  {
    id: '6.05',
    category: 'A',
    categoryNumber: 6,
    categoryName: 'Werkzeuge, Beleuchtungsgeräte und sonstige Einsatzgeräte',
    description: 'Zelt, über 10 Personen',
    unit: 'je Std / 5-12h pauschal',
    price: 0,
    pricePauschal: 65.8,
    isExtendable: false,
    sortOrder: 605,
  },
  {
    id: '6.06',
    category: 'A',
    categoryNumber: 6,
    categoryName: 'Werkzeuge, Beleuchtungsgeräte und sonstige Einsatzgeräte',
    description: 'Wärmebildkamera',
    unit: 'je Std / 5-12h pauschal',
    price: 38.8,
    pricePauschal: 194.0,
    isExtendable: false,
    sortOrder: 606,
  },
  {
    id: '6.07',
    category: 'A',
    categoryNumber: 6,
    categoryName: 'Werkzeuge, Beleuchtungsgeräte und sonstige Einsatzgeräte',
    description: 'Schnelleinsatzzelt (gegebenenfalls mit Beheizung)',
    unit: 'je Std / 5-12h pauschal',
    price: 58.3,
    pricePauschal: 291.5,
    isExtendable: false,
    sortOrder: 607,
  },

  // ==========================================================================
  // Category 7: Persönliche Ausrüstung - Schutzbekleidung - Tarif A
  // ==========================================================================
  {
    id: '7.01',
    category: 'A',
    categoryNumber: 7,
    categoryName: 'Persönliche Ausrüstung - Schutzbekleidung',
    description: 'Hitzeschutzanzug',
    unit: 'je Std / 5-12h pauschal',
    price: 19.4,
    pricePauschal: 97.0,
    isExtendable: false,
    sortOrder: 701,
  },
  {
    id: '7.02',
    category: 'A',
    categoryNumber: 7,
    categoryName: 'Persönliche Ausrüstung - Schutzbekleidung',
    description: 'Hitzeschutzhandschuhe oder Hitzeschutzhaube',
    unit: 'je Std / 5-12h pauschal',
    price: 0,
    pricePauschal: 25.9,
    isExtendable: false,
    sortOrder: 702,
  },
  {
    id: '7.03',
    category: 'A',
    categoryNumber: 7,
    categoryName: 'Persönliche Ausrüstung - Schutzbekleidung',
    description: 'Wathose',
    unit: 'je Std / 5-12h pauschal',
    price: 0,
    pricePauschal: 29.1,
    isExtendable: false,
    sortOrder: 703,
  },

  // ==========================================================================
  // Category 8: Wasserdienst - Tarif A
  // ==========================================================================
  {
    id: '8.01',
    category: 'A',
    categoryNumber: 8,
    categoryName: 'Wasserdienst',
    description: 'Arbeits- bzw. Mehrzweckboot',
    unit: 'je Std / 5-12h pauschal',
    price: 106.9,
    pricePauschal: 534.5,
    isExtendable: false,
    sortOrder: 801,
  },
  {
    id: '8.02',
    category: 'A',
    categoryNumber: 8,
    categoryName: 'Wasserdienst',
    description: 'Zille (ohne Motor)',
    unit: 'je Std / 5-12h pauschal',
    price: 15.1,
    pricePauschal: 75.5,
    isExtendable: false,
    sortOrder: 802,
  },
  {
    id: '8.03',
    category: 'A',
    categoryNumber: 8,
    categoryName: 'Wasserdienst',
    description: 'Schlauchboot, Kunststoffboot (mit Motor)',
    unit: 'je Std / 5-12h pauschal',
    price: 38.8,
    pricePauschal: 194.0,
    isExtendable: false,
    sortOrder: 803,
  },
  {
    id: '8.04',
    category: 'A',
    categoryNumber: 8,
    categoryName: 'Wasserdienst',
    description: 'Schlauchboot, Kunststoffboot (ohne Motor)',
    unit: 'je Std / 5-12h pauschal',
    price: 15.1,
    pricePauschal: 75.5,
    isExtendable: false,
    sortOrder: 804,
  },

  // ==========================================================================
  // Category 9: Einsatzgeräte für den Gefährliche-Stoffe-Einsatz - Tarif A
  // ==========================================================================
  {
    id: '9.01',
    category: 'A',
    categoryNumber: 9,
    categoryName: 'Einsatzgeräte für den Gefährliche-Stoffe-Einsatz',
    description:
      'Explosimeter, Gasspürgerät (Prüfröhrchen als Verbrauchsmaterial)',
    unit: 'je Std / 5-12h pauschal',
    price: 0,
    pricePauschal: 50.7,
    isExtendable: false,
    sortOrder: 901,
  },
  {
    id: '9.02',
    category: 'A',
    categoryNumber: 9,
    categoryName: 'Einsatzgeräte für den Gefährliche-Stoffe-Einsatz',
    description: 'Pauschale für alle übrigen Messgeräte (je Gerät)',
    unit: 'je Std / 5-12h pauschal',
    price: 0,
    pricePauschal: 75.6,
    isExtendable: false,
    sortOrder: 902,
  },
  {
    id: '9.03',
    category: 'A',
    categoryNumber: 9,
    categoryName: 'Einsatzgeräte für den Gefährliche-Stoffe-Einsatz',
    description: 'Strahlenmessgerät',
    unit: 'je Std / 5-12h pauschal',
    price: 21.6,
    pricePauschal: 108.0,
    isExtendable: false,
    sortOrder: 903,
  },
  {
    id: '9.04',
    category: 'A',
    categoryNumber: 9,
    categoryName: 'Einsatzgeräte für den Gefährliche-Stoffe-Einsatz',
    description: 'Ölsperren (je 10 lfm)',
    unit: 'je Std / 5-12h pauschal',
    price: 0,
    pricePauschal: 144.7,
    isExtendable: false,
    sortOrder: 904,
  },

  // ==========================================================================
  // Category 10: Tarif für pauschalierte Beistellungen und Einsatzleistungen - Tarif B
  // ==========================================================================
  {
    id: '10.01',
    category: 'B',
    categoryNumber: 10,
    categoryName: 'Tarif für pauschalierte Beistellungen und Einsatzleistungen',
    description:
      'Aufsperren einer Wohnung (gleichgültig ob durch Nachschlüssel, Fenstereinstieg o.ä.)',
    unit: 'nach Aufwand, mind. 55 €',
    price: 0,
    pricePauschal: 55.0,
    isExtendable: true,
    sortOrder: 1001,
  },
  {
    id: '10.02',
    category: 'B',
    categoryNumber: 10,
    categoryName: 'Tarif für pauschalierte Beistellungen und Einsatzleistungen',
    description: 'Freimachen eines Verkehrsweges (§ 89a StVO 1960)',
    unit: 'nach Aufwand',
    price: 0,
    isExtendable: true,
    sortOrder: 1002,
  },
  {
    id: '10.03',
    category: 'B',
    categoryNumber: 10,
    categoryName: 'Tarif für pauschalierte Beistellungen und Einsatzleistungen',
    description: 'Anschleppen eines Kraftfahrzeuges',
    unit: 'nach Aufwand, mind. 72,30 €',
    price: 0,
    pricePauschal: 72.3,
    isExtendable: true,
    sortOrder: 1003,
  },
  {
    id: '10.04',
    category: 'B',
    categoryNumber: 10,
    categoryName: 'Tarif für pauschalierte Beistellungen und Einsatzleistungen',
    description:
      'Personenbefreiung aus Aufzügen (max. 30 Min., darüber hinaus nach Aufwand)',
    unit: '259,20 € bzw. nach Aufwand',
    price: 0,
    pricePauschal: 259.2,
    isExtendable: true,
    sortOrder: 1004,
  },
  {
    id: '10.05',
    category: 'B',
    categoryNumber: 10,
    categoryName: 'Tarif für pauschalierte Beistellungen und Einsatzleistungen',
    description:
      'Wassertransport nur Tanklöschfahrzeug bis 2.000 l mit Fahrer (Pauschale)',
    unit: '73,40 € je Fahrt bzw. nach Aufwand',
    price: 0,
    pricePauschal: 73.4,
    isExtendable: true,
    sortOrder: 1005,
  },
  {
    id: '10.06',
    category: 'B',
    categoryNumber: 10,
    categoryName: 'Tarif für pauschalierte Beistellungen und Einsatzleistungen',
    description:
      'Wassertransport nur Tanklöschfahrzeug > 2.000 – 4.000 l mit Fahrer (Pauschale)',
    unit: '99,30 € je Fahrt bzw. nach Aufwand',
    price: 0,
    pricePauschal: 99.3,
    isExtendable: true,
    sortOrder: 1006,
  },
  {
    id: '10.07',
    category: 'B',
    categoryNumber: 10,
    categoryName: 'Tarif für pauschalierte Beistellungen und Einsatzleistungen',
    description:
      'Wassertransport nur Tanklöschfahrzeug > 4.000 – 10.000 l mit Fahrer (Pauschale)',
    unit: '129,60 € je Fahrt bzw. nach Aufwand',
    price: 0,
    pricePauschal: 129.6,
    isExtendable: true,
    sortOrder: 1007,
  },

  // ==========================================================================
  // Category 11: Tarif für Brandschutzanlagen - Tarif C
  // ==========================================================================
  {
    id: '11.01',
    category: 'C',
    categoryNumber: 11,
    categoryName: 'Tarif für Brandschutzanlagen',
    description: 'Anschaltung mittels Übertragungssystem gemäß ÖNORM EN 54-21, Typ 1',
    unit: 'pro Monat',
    price: 0,
    pricePauschal: 112.3,
    isExtendable: false,
    sortOrder: 1101,
  },
  {
    id: '11.02',
    category: 'C',
    categoryNumber: 11,
    categoryName: 'Tarif für Brandschutzanlagen',
    description: 'Anschaltung mittels Übertragungssystem gemäß ÖNORM EN 54-21, Typ 2',
    unit: 'pro Monat',
    price: 0,
    pricePauschal: 99.3,
    isExtendable: false,
    sortOrder: 1102,
  },
  {
    id: '11.03',
    category: 'C',
    categoryNumber: 11,
    categoryName: 'Tarif für Brandschutzanlagen',
    description:
      'Dauerhafte Aktivierung oder Deaktivierung eines Anschlusses einer Brandschutzanlage an die öffentliche Alarmeinrichtung der Feuerwehr',
    unit: 'je Fall',
    price: 45.0,
    isExtendable: false,
    sortOrder: 1103,
  },
  {
    id: '11.04',
    category: 'C',
    categoryNumber: 11,
    categoryName: 'Tarif für Brandschutzanlagen',
    description: 'Brandmelder Fehl- oder Täuschungsalarm',
    unit: 'nach Aufwand entsprechend der alarmplanmäßigen Ausrückung, mind. 421,20 €',
    price: 0,
    pricePauschal: 421.2,
    isExtendable: true,
    sortOrder: 1104,
  },
  {
    id: '11.05',
    category: 'C',
    categoryNumber: 11,
    categoryName: 'Tarif für Brandschutzanlagen',
    description:
      'Durch Personen weitergeleitete Fehl- oder Täuschungsalarme, Alarme von Rauchwarnmeldern („Home-Rauchmelder")',
    unit: 'pauschal',
    price: 0,
    pricePauschal: 54.0,
    isExtendable: false,
    sortOrder: 1105,
  },
  {
    id: '11.06',
    category: 'C',
    categoryNumber: 11,
    categoryName: 'Tarif für Brandschutzanlagen',
    description:
      'Durch ohne gesetzliches Erfordernis automatisch weitergeleitete Fehl- oder Täuschungsalarme, von Rauchwarnmeldern (auch als Teil von Gefahrenmeldeanlagen) automatisch weitergeleitete Fehl oder Täuschungsalarme',
    unit: 'pauschal',
    price: 0,
    pricePauschal: 456.8,
    isExtendable: false,
    sortOrder: 1106,
  },
  {
    id: '11.07',
    category: 'C',
    categoryNumber: 11,
    categoryName: 'Tarif für Brandschutzanlagen',
    description: 'Vidierung von Brandschutzplänen',
    unit: 'Grundbetrag 21,60 €, je Bogen zusätzlich 5,40 €',
    price: 5.4,
    pricePauschal: 21.6,
    isExtendable: false,
    sortOrder: 1107,
  },

  // ==========================================================================
  // Category 12: Tarif für Verbrauchsmaterialien - Tarif D
  // ==========================================================================
  {
    id: '12.01',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description:
      'Kraftstoffe, Öle, Reinigungsmittel (zB Benzin, Gemisch, Dieselkraftstoff, Motoröl, Petroleum)',
    unit: 'Die Berechnung erfolgt zu den Tagespreisen',
    price: 1.8,
    isExtendable: true,
    sortOrder: 1201,
  },
  {
    id: '12.02',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description: 'Pölzmaterial (zB Gerüstklammer, Holz jeder Art)',
    unit: 'Die Berechnung erfolgt zu den Tagespreisen',
    price: 0,
    isExtendable: true,
    sortOrder: 1202,
  },
  {
    id: '12.03',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description:
      'Atemschutzmaterial (zB Alkalipatrone für Sauerstoffschutzgerät, Alkalipatrone für Tauchgerät, Atemfilter, Fluchthauben)',
    unit: 'Die Berechnung erfolgt zu den Tagespreisen',
    price: 0,
    isExtendable: true,
    sortOrder: 1203,
  },
  {
    id: '12.04',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description:
      'Sonstiges Verbrauchsmaterial (zB Schweißgas, Löschpulver, Netzmittel, Bindemittel jeder Art, Ölsaugmaterial [Sorbtücher, -watte, -netzsperre], Sägespäne, Torfmull, Pressluft, Sauerstoff - med. rein, Prüfröhrchen, Schaummittel, Stickstoff, Trennscheiben, Treibladung für Leinenschießgerät usw.)',
    unit: 'Die Berechnung erfolgt zu den Tagespreisen',
    price: 0,
    isExtendable: true,
    sortOrder: 1204,
  },
  {
    id: '12.05',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description: 'Sack Ölbindemittel',
    unit: 'pro Sack',
    price: 49.0,
    isExtendable: false,
    sortOrder: 1205,
  },
  {
    id: '12.06',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description: 'Einweg Overall Flüssigkeitsbeständig',
    unit: 'pro Stück',
    price: 39.0,
    isExtendable: false,
    sortOrder: 1206,
  },
  {
    id: '12.07',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description: 'Einweg Overall Schutzstuffe 2 (Apollo)',
    unit: 'pro Stück',
    price: 81.6,
    isExtendable: false,
    sortOrder: 1207,
  },
  {
    id: '12.08',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description: 'Schutzanzug Splash 600 Mehrweg (Stufe 2)',
    unit: 'pro Stück',
    price: 246.0,
    isExtendable: false,
    sortOrder: 1208,
  },
  {
    id: '12.09',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description: 'Apollo 4000 Schutzanzug LFK',
    unit: 'pro Stück',
    price: 177.6,
    isExtendable: false,
    sortOrder: 1209,
  },
  {
    id: '12.10',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description: 'Kombifilter A2B2E2K2HgP3 R SL',
    unit: 'pro Stück',
    price: 43.8,
    isExtendable: false,
    sortOrder: 1210,
  },
  {
    id: '12.11',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description: 'Chemalikenbinder',
    unit: 'pro Stück',
    price: 60.0,
    isExtendable: false,
    sortOrder: 1211,
  },
  {
    id: '12.12',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description: 'Dekon Tauchpumpe',
    unit: 'pro Stück',
    price: 100.0,
    isExtendable: false,
    sortOrder: 1212,
  },
  {
    id: '12.13',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description: 'Adapter PA auf RA für Filtermaske',
    unit: 'pro Stück',
    price: 51.9,
    isExtendable: false,
    sortOrder: 1213,
  },
  {
    id: '12.14',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description: 'Handschuhe AlphaTec (Chemikalienbeständig)',
    unit: 'pro Stück',
    price: 19.2,
    isExtendable: false,
    sortOrder: 1214,
  },
  {
    id: '12.15',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description: 'Reinigungspauschale',
    unit: 'pro Stück',
    price: 500.0,
    isExtendable: false,
    sortOrder: 1215,
  },
  {
    id: '12.16',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description: 'Entsorgungspauschale',
    unit: 'pro Stück',
    price: 200.0,
    isExtendable: false,
    sortOrder: 1216,
  },
  {
    id: '12.17',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description: 'Europalette',
    unit: 'pro Stück',
    price: 50.0,
    isExtendable: false,
    sortOrder: 1217,
  },
  {
    id: '12.18',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description: '300 Liter IBC Container (UN)',
    unit: 'pro Stück',
    price: 190.8,
    isExtendable: false,
    sortOrder: 1218,
  },
  {
    id: '12.19',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description: '600 Liter IBC Container (UN)',
    unit: 'pro Stück',
    price: 258.0,
    isExtendable: false,
    sortOrder: 1219,
  },
  {
    id: '12.20',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description: '1000 Liter IBC Container (UN)',
    unit: 'pro Stück',
    price: 380.4,
    isExtendable: false,
    sortOrder: 1220,
  },
  {
    id: '12.21',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description: 'Prüfung Schutzstufe 3',
    unit: 'pro Stück',
    price: 370.0,
    isExtendable: false,
    sortOrder: 1221,
  },
  {
    id: '12.22',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description: 'Kettengehänge 2-Strang (4m)',
    unit: 'pro Stück',
    price: 600.0,
    isExtendable: false,
    sortOrder: 1222,
  },
  {
    id: '12.23',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description: 'Unterlegplane',
    unit: 'pro Stück',
    price: 50.0,
    isExtendable: false,
    sortOrder: 1223,
  },
  {
    id: '12.24',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description: 'Fass 60l',
    unit: 'pro Stück',
    price: 60.0,
    isExtendable: false,
    sortOrder: 1224,
  },
  {
    id: '12.25',
    category: 'D',
    categoryNumber: 12,
    categoryName: 'Tarif für Verbrauchsmaterialien',
    description: 'SPC 4800 - Schutzanzug',
    unit: 'pro Stück',
    price: 280.0,
    isExtendable: false,
    sortOrder: 1225,
  },
];

/**
 * Get default rates with version information included
 */
export function getDefaultRatesWithVersion(): KostenersatzRate[] {
  return DEFAULT_RATES.map((rate) => ({
    ...rate,
    version: DEFAULT_VERSION_ID,
    validFrom: DEFAULT_VERSION.validFrom,
  }));
}

/**
 * Get rates grouped by category number
 */
export function groupRatesByCategory(
  rates: KostenersatzRate[]
): Map<number, KostenersatzRate[]> {
  const grouped = new Map<number, KostenersatzRate[]>();

  for (const rate of rates) {
    const existing = grouped.get(rate.categoryNumber) || [];
    existing.push(rate);
    grouped.set(rate.categoryNumber, existing);
  }

  // Sort each group by sortOrder
  grouped.forEach((value, key) => {
    grouped.set(
      key,
      value.sort((a, b) => a.sortOrder - b.sortOrder)
    );
  });

  return grouped;
}

/**
 * Get unique category names with their numbers
 */
export function getCategoryList(
  rates: KostenersatzRate[]
): Array<{ number: number; name: string }> {
  const seen = new Set<number>();
  const categories: Array<{ number: number; name: string }> = [];

  for (const rate of rates.sort((a, b) => a.sortOrder - b.sortOrder)) {
    if (!seen.has(rate.categoryNumber)) {
      seen.add(rate.categoryNumber);
      categories.push({
        number: rate.categoryNumber,
        name: rate.categoryName,
      });
    }
  }

  return categories;
}
